#!/system/bin/mksh
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.


#sdcard="$(readlink -f /sdcard)"
home="$ANDROID_DATA/local"
system="$(basename $0)"
imgtype="ext2"
shell="/bin/bash"
ramdisk="/mnt/ramdisk"
command="$1"

#export xbin="$ANDROID_ROOT/xbin"
#export PATH="$xbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH"
#export TERM="xterm-color"
#export HOME="/root"


if [ -z "$SECONDARY_STORAGE" ]; then
  sdcard="$EXTERNAL_STORAGE"
  #sdcard="$(df -P "/dev/block/mmcblk0p1" | awk '{ print $6 }' | tail -n 1 )"
else
  intern="$EXTERNAL_STORAGE"
  sdcard="$SECONDARY_STORAGE"
fi



#kit="$(currentscriptpath)"
#img="$kit/$system.img"



# Start Main function
function_main
