#!/system/bin/sh
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.

#sdcard="$(readlink -f /sdcard)"
home="$ANDROID_DATA/local"
system="$(basename $0)"
mnt="$ANDROID_DATA/local/$system"
imgtype="ext2"
shell="/bin/bash"
ramdisk="/mnt/ramdisk"

export xbin="$ANDROID_ROOT/xbin"
export PATH="$xbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH"
export TERM="xterm-color"
export HOME="/root"


if [ -z "$SECONDARY_STORAGE" ]; then
  sdcard="$EXTERNAL_STORAGE"
else
  intern="$EXTERNAL_STORAGE"
  sdcard="$SECONDARY_STORAGE"
fi

currentscriptpath()
{
  local fullpath=`echo "$(readlink -f $0)"`
  local fullpath_length=`echo ${#fullpath}`
  local scriptname="$(basename "$fullpath")"
  local scriptname_length=`echo ${#scriptname}`
  local result_length=`echo $((fullpath_length - $scriptname_length - 1))`
  local result=`echo "$fullpath" | head -c $result_length`
  echo "$result"
}

getloopno()
{
for i in $(seq 255 -1 0); do
  if [ ! -e "/dev/block/loop$i" ]; then
    echo $i
    return
  fi
done
}

#kit="$(currentscriptpath)"
#img="$kit/$system.img"


if [ "$1" != "install" ]; then
  ##-------------------------Check Arguments--------------------------##
  for (( i=$((BASH_ARGC - 1)); $((i >= 0)); i=$((i - 1)) )); do
    if [ "$(echo "${BASH_ARGV[$i]}" | head -c 2)" == "--" ];then
      case "$arg" in
      ##-----------------------Config Path----------------------------##
      --config)
        echo "WARNING: Do not change the default config path."
        i=$((i - 1))
        config_path="${BASH_ARGV[$i]}"
        break
      ;;
      ##-----------------------System User Home-----------------------##
      --home)
        echo "WARNING: Do not change the default home path."
        i=$((i - 1))
        arg_home="${BASH_ARGV[$i]}"
      ;;
      esac
    fi
  done
  
  
  if [ -z "$config_path" ]; then
    config_path="$home/linuxonandroid"
  fi
  
  
  #Froyo's apps-to-SD makes use of special loopback devices /dev/block/dm-#
  #Each program installed to SD uses up a normal loopback device.
  #We therefore have to make our own with a minor number that we hope
  #users will never reach.
  #Our mount will break if there are $loopno apps installed to SD

  if [ -e "$config_path/config.default" ]; then
    . "$config_path/config.default"
  fi
  if [ -e "$config_path/config.$system" ]; then
    . "$config_path/config.$system"
  fi
fi




##---------------------------Check Arguments--------------------------##
for (( i=$((BASH_ARGC - 1)); $((i >= 0)); i=$((i - 1)) )); do
  curr_arg="${BASH_ARGV[$i]}"
  if [ -z "$curr_arg" ]; then
    :
  elif [ "$curr_arg" == "-h" ] || [ "$curr_arg" == "--help" ]; then
    arg_help=true
    break
  #elif [ "$(echo "$curr_arg" | head -c 2)" == "--" ];then
  elif echo "$curr_arg" | grep -qxE -e '--[a-zA-Z\-\_]+';then
    case "echo "$curr_arg" | grep -oE -e '--[a-zA-Z\-\_]+'" in
    ##-------------------------Architecture---------------------------##
    #--android)
    #  arg_android="true"
    #;;
    ##-------------------------Architecture---------------------------##
    --architecture)
      i=$((i - 1))
      architecture="${BASH_ARGV[$i]}"
      arg_arch="true"
    ;;
    ##-------------------------Install Path of linux Script-----------##
    --bin)
      i=$((i - 1))
      arg_bin="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------Config Path----------------------------##
    --config)
      echo "WARNING: Do not change the default config path."
      i=$((i - 1))
      config_path="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------System User Home-----------------------##
    --home)
      echo "WARNING: home"
      i=$((i - 1))
      arg_home="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------Image Path-----------------------------##
    --img)
      i=$((i - 1))
      img="${BASH_ARGV[$i]}"
      arg_img="true"
    ;;
    ##-------------------------Initialize-----------------------------##
    --init)
      arg_init="true"
    ;;
    ##-------------------------Mount Path-----------------------------##
    --mnt)
      i=$((i - 1))
      mnt="${BASH_ARGV[$i]}"
      arg_mnt="true"
    ;;
    ##-------------------------Mount Path-----------------------------##
    --mnt-options)
      i=$((i - 1))
      imgoptions="${BASH_ARGV[$i]}"
      arg_imgoptions="true"
    ;;
    ##-------------------------Use native mount-----------------------##
    --native)
      native="true"
    ;;
    ##-------------------------Use native mount-----------------------##
    --partition)
      i=$((i - 1))
      partition="${BASH_ARGV[$i]}"
      arg_partition="true"
    ;;
    ##-------------------------System PATH----------------------------##
    --path)
      i=$((i - 1))
      arg_path_abs="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------System PATH----------------------------##
    --post-path)
      i=$((i - 1))
      arg_path_post="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------System PATH----------------------------##
    --pre-path)
      i=$((i - 1))
      arg_path_pre="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------System Name----------------------------##
    --system)
      if [ "$1" == "install" ]; then
        # The script must be installed or renamed to work correctly
        arg_system="true"
        i=$((i - 1))
        system="${BASH_ARGV[$i]}"
      fi
    ;;
    ##-------------------------System TERM----------------------------##
    --term)
      i=$((i - 1))
      arg_term="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------System Name----------------------------##
    --type)
      # The script must be installed or renamed to work correctly
      arg_imgtype="true"
      i=$((i - 1))
      imgtype="${BASH_ARGV[$i]}"
    ;;
    ##-------------------------Unknown Argument-----------------------##
    #*)
    #  echo -e "$0: unknown argument: $curr_arg\n"
    #  "$0" -h
    #  exit 2 #TODO set the standard return value for this case
    #;;
    esac
  elif echo "$curr_arg" | grep -qxE -e '--[a-zA-Z\-\_]+=';then
    case "$(echo "$curr_arg" | grep -oE -e '--[a-zA-Z\-\_]+=')" in
    ##-------------------------Port for SSH---------------------------##
    --ssh-port=)
      sshport="$(echo "$curr_arg" | awk -F "=" '{print $2}')"
      if ! echo "$sshport" | grep -qE -e '^[0-6]?[0-9]?[0-9]?[0-9]?[0-9]'; then # FIXME this is not correct
        echo "ERROR: Wrong port."
        exit 2
      fi
      if [ "$((sshport > 0 && sshport <= 65535))" == "1" ]; then
        echo "ERROR: Wrong port."
        exit 2
      fi
    ;;
    esac
  elif [ "$(echo -"$curr_arg" | head -c 2)" == "--" ];then
  elif echo "$curr_arg" | grep -qxE -e '-[a-zA-Z]+';then
    #args="$(echo -"$curr_arg" | awk 'BEGIN{FS=""}{ for (i = 3; i <= NF; ++i) print $i; }')"
    args="$(echo "$curr_arg" | grep -oE -e '-[a-zA-Z]+')"

    for arg in `echo -e "$args"`; do
      case "$arg" in
    ##-------------------------System Name----------------------------##
      s)
        arg_system="true"
        i=$((i - 1))
        system="${BASH_ARGV[$i]}"
      ;;
      ##-----------------------Unknown--------------------------------##
      #*)
      #  echo -e "$0: unknown argument: -$arg\n"
      #  "$0" -h
      #  exit 2 #TODO set the standard return value for this case
      #;;
      esac
    done
  else
    ##-------------------------Unknown Argument-----------------------##
    if [ -z "$arg_rest" ]; then
      arg_rest="$curr_arg" # FIXME args with linebreaks
    else
      arg_rest="$arg_rest\n$curr_arg"
    fi
    #echo -e "$0: unknown argument: $curr_arg\n"
    #"$0" -h
    #exit 2 #TODO set the standard return value for this case
  fi
done




case "$1" in
mount)
  if [ ! -e "$config_path/config.$system" ]; then
    "$0" install "$system"
    . "$config_path/config.$system"
  fi

  if mount | grep -q " $mnt "; then
    echo "$img already mounted"
    #if [ "$arg_android" == "true" ] && $(mount | ! grep -q " $mnt/mnt/data "); then
    #if [ "$arg_android" == "true" ] && ! mountpoint -q "$mnt/mnt/data"; then
    #  echo "Mounting: System Parts ..."
    #  mount -o bind "$ANDROID_DATA" "$mnt/mnt/data"
    #  mount -o bind "$ANDROID_ROOT" "$mnt/mnt/system"
    #  #if [ -d "/sbin" ]; then
    #  #  mount -o bind /sbin "$mnt/mnt/sbin"
    #  #fi
    #fi
    exit 2
  fi

  echo "Mounting: Prepwork ..."
  #some ROMS mount the sdcard nodev
  mount -o dev,remount "$sdcard"
  #some also don't load filesystem drivers on boot
  grep -q ext2 /proc/filesystems || modprobe ext2

  if [ ! -z "$imgoptions" ]; then
    imgoptions="-o $imgoptions"
  fi

  if [ "$native" == "true" ]; then
    echo "Mounting: Native mount ..."
    mount -t "$imgtype" $imgoptions "$partition" "$mnt"
  else
    echo "Mounting: Loopback mount ..."
    mkdir -p "$mnt"

    loopno=$(getloopno)
    loop="/dev/block/loop$loopno"
    if [ "$loopno" == "" ]; then
      echo "could not mount image, no free loop-devices found"
      exit 6
    fi
    #if [ -e "$loop" ]; then
    #  echo "Remove Loopback Device"
    #  losetup -d "$loop"
    #  rm "$loop"
    #fi
    #create loop device
    mknod "$loop" b 7 "$loopno"
    losetup "$loop" "$img"
    mount -t "$imgtype" $imgoptions "$loop" "$mnt"
    touch "$img"
  fi

  echo "Mounting: Setting up chroot environment ..."
  mount -o bind /dev "$mnt/dev"
  mount -t devpts devpts "$mnt/dev/pts"
  mount -o bind /proc "$mnt/proc"
  mount -o bind /sys "$mnt/sys"

  if [ ! -z "$mountdefault" ]; then
    for comm in $(echo "$mountdefault" | awk 'BEGIN{FS=","}{print $0}'); do
      if [ "$comm" == "sdcard" ]; then # TODO
        #make the SD card accessible to the chroot environment
        mkdir -p "$mnt/mnt/sdcard"
        #mount -o bind $sdcard "$mnt/media/sdcard"
        mount_point=$(df -P | awk '$6=="'$sdcard'" {print $1}')
        mount -t vfat -o rw,dirsync,suid,exec,relatime "$mount_point" "$mnt/mnt/sdcard"
      elif [ "$comm" == "intern" ]; then
      #elif [ "$comm" == "android" ]; then
      elif [ "$comm" == "images" ]; then
        "$0" mountimg $@
      fi
    done

    #if [ "$2" = "android" ]; then
    #  echo "Mounting: System Parts ..."
    #  mount -o bind $ANDROID_DATA "$mnt/mnt/data"
    #  mount -o bind $ANDROID_ROOT "$mnt/mnt/system"
    #  #if [ -d "/sbin" ]; then
    #  #  mount -o bind /sbin "$mnt/mnt/sbin"
    #  #fi
    #fi
  fi

  echo "	[ Done ]"

;;
umount|unmount)
  loop="$(mountpoint -n /data/local/linux/ | cut -sd' ' -f1)"
  if ! losetup "$loop" > /dev/null 2>&1; then
    unset loop
  fi

  sys_pid="$(ps -o pid,comm | awk '/zygote/ {print $1}')"
  mnt_pid="$(fuser -m "$mnt")"

  echo "Kill running processes"
  #fuser -km "$mnt" # TODO replace with include list
  echo "Unmounting ..."
  "$0" umountimg $@
  #awk '{print $2}' /proc/mounts | grep "^$mnt" | sort -r | xargs umount
  cut -sd' ' -f2 /proc/mounts | grep "^$mnt" | sort -r | awk '{system("umount -fl \"" $0 "\"")}'

  if [ -e "$loop" ]; then
    echo "Unmounting: Loopback mount ..."
    losetup -d "$loop"
    rm "$loop"
  fi

;;
mountsd)
  if ! mountpoint -q "$mnt"; then
    echo "$img not mounted"
    exit 3
  fi
  if mountpoint -q "$mnt/mnt/sdcard"; then
    echo "$mnt/mnt/sdcard already mounted"
    exit 4
  fi

  #make the SD card accessible to the chroot environment
  mkdir -p "$mnt/mnt/sdcard"

  #mount -o bind "$sdcard" "$mnt/media/sdcard"
  mount_point=$(df -P | awk '$6=="'$sdcard'" {print $1}')
  mount -t vfat -o rw,dirsync,suid,exec,relatime "$mount_point" "$mnt/mnt/sdcard"

;;
umountsd|unmountsd)
  echo "Kill running processes"
  fuser -km "$mnt/mnt/sdcard"
  echo "Unmounting ..."
  umount -fl "$mnt/mnt/sdcard"

;;
mountimg)
  beg=250
  unset IFS
  conffiles=default'
'"$system"
  for mountconf in $conffiles; do
    if [ -e "/data/local/linuxonandroid/mount.$mountconf" ]; then
      for line in $(cat "/data/local/linuxonandroid/mount.$mountconf" | awk '{print $0}'); do
        IFS=":"
        image="$(echo $line | awk '{ print $1 }')"
        target="$mnt/$(echo $line | awk '{ print $2 }')"
        options="$(echo $line | awk '{ print $3 }')"
        type="$(echo $line | awk '{ print $4 }')"
        unset IFS
        if [ ! -z "$options" ]; then options="-o $options"; else unset options; fi
        if [ -z "$type" ]; then type="ext2"; fi

        if [ "$image" != "" ] && [ "$target" != "" ]; then
          if mountpoint -q "$target" || [ ! -e "$image" ]; then
            continue;
          fi
          for i in $(seq $beg -1 0); do
            if [ ! -e "/dev/block/loop$i" ]; then
              loopno=$i
              beg=$((i-1))
              break
            fi
          done
          echo mount -t "$type" $options "$image" "$target"
          loop="/dev/block/loop$loopno"
          #create loop device
          mknod "$loop" b 7 "$loopno"
          losetup "$loop" "$image"
          mkdir -p "$target"
          mount -t "$type" $options "$loop" "$target"
        fi
      done
    fi
  done

;;
umountimg|unmountimg)
#  echo "Kill running processes"
#  fuser -km "$mnt/mnt/sdcard"
#  echo "Unmounting ..."
#  umount -f "$mnt/mnt/sdcard"

;;
mountram)
  if mount | ! grep -q " $mnt "; then
    echo "$img not mounted"
    exit 5
  fi

  mount -t ramfs ramfs "$mnt/$ramdisk"

;;
umountram)
#  echo "Kill running processes"
#  fuser -km "$mnt/$ramdisk"
  echo "Unmounting ..."
  umount -f "$mnt/$ramdisk"

;;
chroot|"")
  "$0" mount
  chroot "$arg_user" "$mnt" $shell

;;
ssh)
  "$0" mount
  chroot "$mnt" /root/scripts/ssh.sh "$arg_port" "$arg_rest"

;;
vnc)
  "$0" mount
  chroot "$mnt" /root/scripts/vnc.sh $2 $3

;;
install)
  if [ "$2" != "" ]; then
    system="$2"
  fi
  if [ "$3" = "--force" ] || [ "$4" = "--force" ]; then
    force=true
  fi
  if [ ! -z "$3" ] && [ "$3" != "--force" ] && [ "$3" != "--refresh" ]; then
    img="$3"
  fi
  if [ "$3" == "--refresh" ] || [ "$4" == "--refresh" ]; then
    refresh=true
    unset kit
    unset img
    unset mnt
    unset TERM
    if [ -e "$home/linuxonandroid/config.$system" ]; then
      . "$home/linuxonandroid/config.$system"
    fi
  fi
  if [ "$3" == "--noimage" ]; then
    unset img
  fi

  if [ ! -e "$home/linuxonandroid/config.$system" ] || [ "$force" == "true" ] || [ "$refresh" == "true" ]; then
    echo "Creating config files ..."
    mkdir -p /data/local/linuxonandroid
    #echo "kit=\"$kit\"" > "/data/local/linuxonandroid/config.$system"
    echo "img=\"$img\"" >> "/data/local/linuxonandroid/config.$system"

    if [ "$refresh" == "true" ] && [ ! -z "$mnt" ]; then
      echo "mnt=\"$mnt\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "mnt=\"$ANDROID_DATA/local/$system\"" >> "$home/linuxonandroid/config.$system"
    fi
    if [] #TODO
    elif [ "$refresh" == "true" ] && [ ! -z "$native" ]; then
      echo "native=\"$native\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#native=\"false\"" >> "$home/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$architecture" ]; then
      echo "architecture=\"$architecture\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#architecture=\"debian\"" >> "$home/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$partition" ]; then
      echo "partition=\"$partition\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#partition=\"\"" >> "$home/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$imgtype" ]; then
      echo "imgtype=\"$imgtype\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#imgtype=\"ext2\"" >> "$home/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$imgoptions" ]; then
      echo "imgoptions=\"$imgoptions\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#imgoptions=\"\"" >> "$home/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$ramdisk" ]; then
      echo "ramdisk=\"$ramdisk\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#ramdisk=\"/mnt/ramdisk\"" >> "/data/local/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$sshport" ]; then
      echo "sshport=\"$sshport\"" >> "$home/linuxonandroid/config.$system"
    else
      echo "#sshport=\"22\"" >> "/data/local/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$autorun" ]; then
      echo "autorun=\"$autorun\"" >> "/data/local/linuxonandroid/config.$system"
    else
      echo "#autorun=\"run this on\"" >> "/data/local/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$mountdefault" ]; then
      echo "mountdefault=\"$mountdefault\"" >> "/data/local/linuxonandroid/config.$system"
    else
      echo "mountdefault=\"sdcard\" #,intern,android,images,images:default,images:system,images::wireshark,ram" >> "/data/local/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$wlan_if" ]; then
      echo "wlan_if=\"$wlan_if\"" >> "/data/local/linuxonandroid/config.$system"
    else
      echo "#wlan_if=\"wlan0\"" >> "/data/local/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$mobile_if" ]; then
      echo "mobile_if=\"$mobile_if\"" >> "/data/local/linuxonandroid/config.$system"
    else
      echo "#mobile_if=\"rmnet0\"" >> "/data/local/linuxonandroid/config.$system"
    fi
    if [ "$refresh" == "true" ] && [ ! -z "$shell" ]; then
      echo "shell=\"$shell\"" >> "/data/local/linuxonandroid/config.$system"
    else
      echo "#shell=\"/bin/bash\"" >> "/data/local/linuxonandroid/config.$system"
    fi

    echo "export TERM=\"$TERM\"" >> "/data/local/linuxonandroid/config.$system"
    #echo "loopno=\"254\"" >> "/data/local/linuxonandroid/config.$system"
  fi

;;
passwd)
  "$0" mount
  chroot "$mnt" /usr/bin/passwd $2

;;
status)
  echo "Memory (RAM):"
  free
  echo ""
  echo "Swap:"
  cat /proc/swaps

;;
statistic)
  # my wishlist to install + is currently installed
  echo "Memory (RAM):"
  free
  echo ""
  echo "Swap:"
  cat /proc/swaps

;;
space)
  echo "Memory (RAM):"
  free
  echo ""
  echo "Swap:"
  cat /proc/swaps

;;
network)
  #"$0" mount
  #chroot "$mnt" /root/scripts/network.sh "$wlan_if" $@

;;
hardinstall)

;;
help)
  case "$2" in
    "")

    ;;
    mount)
      echo "Mount the Image and system-parts."
    ;;
    mountsd)
      echo "Make the SD card accessible to the chroot environment."
    ;;
    *)
      echo "Command unknown"
    ;;
  esac

;;
*)
  echo "Usage: $(basename $0) [help|[u[n]]mount[sd|img]|chroot|ssh|vnc|install|passwd|hardinstall]"
  exit 1

;;
esac
