#!/system/bin/mksh
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.

##---------------------------Start function_main------------------------------##
function function_main()
{
  function_preCheckArguments
  function_checkArguments

  [[ "$command" != "install" ]] && [ -z "$mnt" ] && mnt="$home/$system"
  [[ -z "$config_path" ]] && config_path="$home/linuxonandroid"


  echo "point1"

  case "$command" in
  mount)
    function_mount

  ;;
  umount|unmount)
    function_umount

  ;;
  mountsd)
    function_mountsd

  ;;
  umountsd|unmountsd)
    function_umountsd

  ;;
  mountimg)
    function_mountimg

  ;;
  umountimg|unmountimg)
    function_umountimg

  ;;
  mountram)
    function_mountram

  ;;
  umountram)
    function_umountram

  ;;
  chroot|"")
    function_mount

    cd "$mnt"
    chroot "$arg_user" "$mnt" $shell

  ;;
  ssh)
    function_mount

    cd "$mnt"
    chroot "$mnt" /opt/android-scripts/ssh.sh "$sshport" "${arg_rest[@]}"
    #eval chroot "$mnt" /opt/android-scripts/ssh.sh "$sshport" $arg_rest

  ;;
  vnc)
    function_mount

    cd "$mnt"
    chroot "$mnt" /opt/android-scripts/vnc.sh "$vncport" "${arg_rest[@]}"
    #eval chroot "$mnt" /opt/android-scripts/vnc.sh "$vncport" "${arg_rest[@]}"

  ;;
  nx)
    function_mount

    cd "$mnt"
    chroot "$mnt" /opt/android-scripts/vnc.sh "$vncport" "${arg_rest[@]}"
    #eval chroot "$mnt" /opt/android-scripts/vnc.sh "$vncport" "${arg_rest[@]}"

  ;;
  http)
    function_mount

    cd "$mnt"
    chroot "$mnt" /opt/android-scripts/http.sh "${arg_rest[@]}"
    #eval chroot "$mnt" /opt/android-scripts/http.sh "${arg_rest[@]}"

  ;;
  install)
    function_install

  ;;
  passwd)
    function_mount

    cd "$mnt"
    chroot "$mnt" /usr/bin/passwd "${arg_rest[@]}"   #FIXME Check if this is an user

  ;;
  status)
    #echo "currently not implemented"
    echo -n "Current CPU Frequency: "
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
    echo -n "Minimum CPU Frequency: "
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
    echo -n "Maximum CPU Frequency: "
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
    #echo "Memory (RAM):"
    #free
    #echo ""
    #echo "Swap:"
    #cat /proc/swaps

  ;;
  statistic)
    # my wishlist to install + is currently installed
    # htop, tmux, ssh, vnc, chroot, truecrypt
    echo "currently not implemented"
    #echo "Memory (RAM):"
    #free
    #echo ""
    #echo "Swap:"
    #cat /proc/swaps

  ;;
  space)
    echo "Memory (RAM):"
    free
    echo ""
    echo "Swap:"
    cat /proc/swaps

  ;;
  network|nw)
    #function_mount

    #cd "$mnt"
    #chroot "$mnt" /opt/android-scripts/network.sh "$wlan_if" $@

  ;;
  hardinstall)

  ;;
  help)
    function_help

  ;;
  *)
    echo "Usage: $(basename $0) [help|[u[n]]mount[sd|img]|chroot|ssh|vnc|nx|http|install|passwd|hardinstall]"
    exit 1

  ;;
  esac
} #end Main

