#!/system/bin/mksh
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.

function currentscriptpath()
{
  local fullpath=`echo "$(readlink -f $0)"`
  local fullpath_length=`echo ${#fullpath}`
  local scriptname="$(basename "$fullpath")"
  local scriptname_length=`echo ${#scriptname}`
  local result_length=`echo $((fullpath_length - $scriptname_length - 1))`
  local result=`echo "$fullpath" | head -c $result_length`
  echo "$result"
}

function getloopno()
{
   if [ -n "$1" ] && `echo "$1" | grep -qEe '^[0-9][0-9]?[0-9]?$'` && (($1 <= 255)); then
      if [ ! -e "/dev/block/loop$1" ]; then
         echo $1
      fi
      return
   fi

   for i in $(seq 255 -1 0); do
      if [ ! -e "/dev/block/loop$i" ]; then
         echo $i
         return
      fi
   done
}

